### ISSUE TITLE
User can't use all default names

### ISSUE THREAD

**Issue by jgao222** [Husky-Coding-Project/battleship#18]
It seems the current controller rejects all empty inputs and just waits for another line if it sees one is empty. While generally it is good to not react to empty input, I am thinking that in the case where we prompt the user for freeform input, like when specifying names during the settings phase, it might be desirable to leave it empty and go with default names.

This currently isn't possible, we would need to
- Remove the guard clause checking it
- add error handling/edge case checking to every method called by the main controller `handleInput` to react correctly to empty strings

This could be alleviated by using the `parsePoint` method introduced in #17, at least for the methods that involve parsing points out of the input.

**Comment by edward-qin** [comment]
I'm thinking maybe instead of checking the handInput in all the other phases, we could move the guard clause into only the cases/phases after the settingsPhase. It looks like the settingsPhase is already checking and doing different behavior for when the input is empty, so it should be easy to make the settingsPhase do different behavior within that method.

**Comment by jgao222** [comment]
Fixed in 34c033192913417bafd4ffa6cbc782dbf54a858c and 334637a6acb4b05d153b49b25ab48132a2c35dae - just added some extra checks
